name: Test Student Submissions

env:
  JAVA_VERSION: "11"
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  SONAR_PROJECT_KEY: "submission-project"
  SONAR_ORG: "organization-key"
  SONAR_HOST_URL: "https://sonarcloud.io"


on:
  push:
    branches:
      - main
 # workflow_dispatch:
 #   inputs:
 #     sonar_token:
 #       description: 'SonarQube Token'
 #       required: true

jobs:
   test-submissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Org Repository
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
          java-version: 17
          distribution: 'temurin'

    - name: Read Repositories
      id: read-repos
      run: |
        repos=$(cat repositories.txt | jq -R -s -c 'split("\n") | map(select(. != ""))')
        echo "REPO_LIST=$repos" >> $GITHUB_ENV

    - name: Process Each Repository
      uses: actions/checkout@v3
      with:
        repository:  ${{ fromJson(env.REPO_LIST)[0] }} 

    - name: Run Maven Tests
      run: |
        mvn clean verify


    - name: Code Coverage Report
      run: |
        mvn jacoco:report


    - name: Send Slack Notification on Success
      if: success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}  # Slack webhook set in GitHub secrets
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "🎉 Build and analysis succeeded for Test Student Submissions!",
          "attachments": [
            {
              "color": "good",
              "text": "The build and analysis for the main branch were successful."
            }
          ]
        }' $SLACK_WEBHOOK

    - name: Send Slack Notification on Failure
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "❌ Build failed for Test Student Submissions!",
          "attachments": [
            {
              "color": "danger",
              "text": "The pipeline failed. Please check the logs for details."
            }
          ]
        }' $SLACK_WEBHOOK
