name: Test Student Submissions

env:
  JAVA_VERSION: "11"
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  SONAR_PROJECT_KEY: "submission-project"
  SONAR_ORG: "organization-key"
  SONAR_HOST_URL: "https://sonarcloud.io"


on:
  workflow_dispatch:
    inputs:
      sonar_token:
        description: 'SonarQube Token'
        required: true

jobs:
  test-submissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Org Repository
      uses: actions/checkout@v3

    - name: Read Repositories
      id: read-repos
      run: |
        repos=$(cat repositories.txt | jq -R -s -c 'split("\n") | map(select(. != ""))')
        echo "REPO_LIST=$repos" >> $GITHUB_ENV

    - name: Process Each Repository
      uses: actions/checkout@v3
      with:
        repository: ${{ fromJson(env.REPO_LIST)[0] }} # Replace 0 with index in a loop
        token: ${{ secrets.REPO_GITHUB_TOKEN }}

    - name: Run Maven Tests
      run: |
        mvn clean verify

    - name: Code Coverage Report
      run: |
        mvn jacoco:report

    - name: SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.sonar_token }}
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=test-cases \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
