name: CI/CD Pipeline

on:
#  workflow_dispatch: # Enables manual trigger of the workflow from the GitHub Actions interface
  push:
     branches:
         - main

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Convert repositories.txt to JSON (Optional if REPO_LIST secret is already added)
      - name: Convert repositories.txt to JSON
        id: convert-repos
        run: |
          repos=$(cat repositories.txt | jq -R . | jq -s .)
          echo "::set-output name=json::$repos"
        shell: bash
        env:
          REPO_FILE: repositories.txt

      # Export REPO_LIST secret
      - name: Set REPO_LIST Secret
        run: |
          echo ${{ steps.convert-repos.outputs.json }}

      # Build and test with Maven
      - name: Build and Test with Maven
        run: mvn clean verify

      # Run Checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:check

      # Run JaCoCo and generate coverage report
      - name: Generate Coverage Report
        run: mvn jacoco:report

      # Upload JaCoCo coverage to Codecov
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      # SonarQube analysis
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=your_organization_name
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
