name: Test Submissions

on:
  workflow_dispatch: # Manual trigger for flexibility

jobs:
  test-submissions:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout your repository
    - name: Checkout Test Framework Repo
      uses: actions/checkout@v3

    # 2. Set up Java
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'

    # 3. Read repositories and clone them
    - name: Read and Clone Repositories
      id: clone-repos
      run: |
        mkdir -p submissions
        while IFS= read -r repo; do
          echo "Cloning $repo..."
          git clone "https://github.com/$repo.git" submissions/$(basename $repo)
        done < repositories.txt

    # 4. Iterate through each cloned repository
    - name: Test Each Submission
      run: |
        for repo in submissions/*; do
          echo "Testing $(basename $repo)..."
          cd $repo
          mvn clean verify -Dcheckstyle.skip=true || echo "Tests failed for $(basename $repo)"
          cd ../..
        done

    # 5. Collect and upload reports
    - name: Upload Test Results
      if: always() # Run even if some repositories fail
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/target/surefire-reports/*'
